### ISSUE TITLE
Error running create-authority command

### ISSUE THREAD

**Issue by tfe** [getsidetrack/swift-device-authority#6]
I get this during the "Creating a unique RSA private key with your chosen password" step:

```
ShellOut encountered an error
Status code: 1
Message: "Extra arguments given.
genrsa: Use -help for summary."
Output: ""
```

I believe it's because of the argument order to `openssl genrsa` on [this line](https://github.com/getsidetrack/swift-device-authority/blob/main/Sources/CommandLine/CreateAuthorityComamnd.swift#L137):

```
openssl genrsa -aes256 -out SwiftDeviceAuthority.key 4096 -passout pass:\(password!)
```

I think the `4096` (`numbits` arg) needs to be at the end.

**Comment by Sherlouk** [comment]
Thanks for highlighting Todd. Could you share which version of OpenSSL you have installed please? I think this might be a case where different versions are handling the ordering slightly differently - this is passing for me locally, but could be that a newer version is more strict on ordering as you suggest.

Will try moving it to the end too as that seems to back the documentation more.

**Comment by tfe** [comment]
Interesting! I've got:

OpenSSL 3.0.3 3 May 2022 (Library: OpenSSL 3.0.3 3 May 2022)

macOS Monterey but I think this version of OpenSSL was installed by homebrew.

But yes the help text was my clue that the arg ordering might be the problem:

```
$ openssl genrsa -help
Usage: genrsa [options] numbits

General options:
 -help               Display this summary
 -engine val         Use engine, possibly a hardware device

Input options:
 -3                  (deprecated) Use 3 for the E value
 -F4                 Use the Fermat number F4 (0x10001) for the E value
 -f4                 Use the Fermat number F4 (0x10001) for the E value

Output options:
 -out outfile        Output the key to specified file
 -passout val        Output file pass phrase source
 -primes +int        Specify number of primes
 -verbose            Verbose output
 -traditional        Use traditional format for private keys
 -*                  Encrypt the output with any supported cipher

Random state options:
 -rand val           Load the given file(s) into the random number generator
 -writerand outfile  Write random data to the specified file

Provider options:
 -provider-path val  Provider load path (must be before 'provider' argument if required)
 -provider val       Provider to load (can be specified multiple times)
 -propquery val      Property query used when fetching algorithms

Parameters:
 numbits             Size of key in bits
```

**Comment by Sherlouk** [comment]
Definitely a version incompatibility, spent some more time on this today.

`which openssl` => `/usr/bin/openssl`
`openssl version` => `LibreSSL 3.3.6`

```
➜  DeviceAuthority git:(main) ✗ openssl genrsa help
usage: genrsa [-3 | -f4] [-aes128 | -aes192 | -aes256 |
    -camellia128 | -camellia192 | -camellia256 | -des | -des3 | -idea]
    [-out file] [-passout arg] [numbits]

 -3                 Use 3 for the E value
 -f4                Use F4 (0x10001) for the E value
 -F4                Use F4 (0x10001) for the E value
 -aes128            Encrypt PEM output with CBC AES
 -aes192            Encrypt PEM output with CBC AES
 -aes256            Encrypt PEM output with CBC AES
 -camellia128       Encrypt PEM output with CBC Camellia
 -camellia192       Encrypt PEM output with CBC Camellia
 -camellia256       Encrypt PEM output with CBC Camellia
 -des               Encrypt the generated key with DES in CBC mode
 -des3              Encrypt the generated key with DES in EDE CBC mode (168 bit key)
 -out file          Output the key to 'file'
 -passout arg       Output file passphrase source
```

It seems that `numbits` is at the end of the usage here, but it actually doesn't enforce it. I've generated both an authority and a leaf, both finished successfully. 

Always difficult to patch without having the error but given the usage documentation suggests it should be at the end, and given that moving it to the end still works fine for me, I'm going to push that change on faith. Looking at your 'help' output it would seem the other parameters are fine, and nothing is jumping out in the other commands either.

I've published a new release with the updated binary, if you wouldn't mind giving it a go and see if it addresses the problem. Thanks 😄
